// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from './application'
import SlimSelectController from './slim_select_controller.js'
import ReturnToTopController from './return_to_top_controller.js'

application.register('slim-select', SlimSelectController)
application.register('return-to-top', ReturnToTopController)
