// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { Controller } from '@hotwired/stimulus'
import SlimSelect from 'slim-select'
require('slim-select/dist/slimselect.css')

export default class extends Controller {
  static targets = []

  connect() {
    console.log('slim select start')
    this.select = new SlimSelect({
      select: this.element,
      addable: function (value) {
        return value
      },
    })
  }
}
